-- liquibase formatted sql
-- changeset core:update_db_verifybackurl-1.0.3-1.0.4-mariaDB-mySQL.sql dbms:mariadb,mysql
-- preconditions onFail:MARK_RAN onError:WARN
ALTER TABLE verifybackurl_authorized_url modify COLUMN id_authorized_url int AUTO_INCREMENT;

-- changeset core:update_db_verifybackurl-1.0.3-1.0.4-postgreSQL.sql dbms:postgresql
-- preconditions onFail:MARK_RAN onError:WARN
ALTER TABLE verifybackurl_authorized_url alter id_authorized_url add GENERATED by default AS IDENTITY(START WITH 1);

-- The query below is used to synchronize the sequence created previously with the content of unittree_unit table.
SELECT setval((SELECT PG_GET_SERIAL_SEQUENCE('"verifybackurl_authorized_url"', 'id_authorized_url')), (SELECT MAX(id_authorized_url) FROM verifybackurl_authorized_url));
